apiVersion: v1
kind: Service
metadata:
  name: symposium-frontend-service
  labels:
    app: $APP_NAME
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: $APP_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symposium-frontend-deployment
spec:
  replicas: 4
  selector: 
    matchLabels: 
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME

    spec:
      imagePullSecrets:
      - name: $OCIR_SECRET_NAME
      containers:
      - name: $APP_NAME
        image: $PRIVATE_REGISTRY_PATH/$TENANCY_NAME/$REPO_NAME/$APP_NAME:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        ports:
        - containerPort: 5000
          protocol: TCP
